# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
    adapter: postgresql
    encoding: unicode
    encoding: utf8
    database: listini_rails_dev
    username: administrator
    password: admin
    host: 127.0.0.1
