# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419d6e98b0e47969c1754d7f3f4f807f855e4c378dc7f1ba5aec9a13a3e844c180659a1a61ce44629613b96cb6e00eb0c5c984348eab7e665e6e826852b97367

test:
  secret_key_base: 9611a5ddd144a3d156d93f9810700dd06231205ed53f0b159bd85d98f0440b3718f27dc433b8fa0eac09c278e09bf881a10d5709be28f9648cafb3fbc8b01d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
